from enum import Enum


class SuitabilityIssueCode(str, Enum):
    # Face presence
    SUITABILITY_NO_FACE = "SUITABILITY_NO_FACE"
    SUITABILITY_MULTIPLE_FACES = "SUITABILITY_MULTIPLE_FACES"
    SUITABILITY_FACE_CHECK_UNAVAILABLE = "SUITABILITY_FACE_CHECK_UNAVAILABLE"
    SUITABILITY_FACE_PROVIDER_FAILED = "SUITABILITY_FACE_PROVIDER_FAILED"

    # Resolution & dimensions
    SUITABILITY_RESOLUTION_TOO_LOW = "SUITABILITY_RESOLUTION_TOO_LOW"
    SUITABILITY_FACE_REGION_TOO_SMALL = "SUITABILITY_FACE_REGION_TOO_SMALL"
    SUITABILITY_RESOLUTION_WARNING = "SUITABILITY_RESOLUTION_WARNING"

    # Blur & focus
    SUITABILITY_BLUR_SEVERE = "SUITABILITY_BLUR_SEVERE"
    SUITABILITY_BLUR_WARNING = "SUITABILITY_BLUR_WARNING"
    SUITABILITY_FOCUS_CHECK_UNCERTAIN = "SUITABILITY_FOCUS_CHECK_UNCERTAIN"

    # Exposure & lighting
    SUITABILITY_UNDEREXPOSED_SEVERE = "SUITABILITY_UNDEREXPOSED_SEVERE"
    SUITABILITY_UNDEREXPOSED_WARNING = "SUITABILITY_UNDEREXPOSED_WARNING"
    SUITABILITY_OVEREXPOSED_SEVERE = "SUITABILITY_OVEREXPOSED_SEVERE"
    SUITABILITY_OVEREXPOSED_WARNING = "SUITABILITY_OVEREXPOSED_WARNING"
    SUITABILITY_LOW_CONTRAST_WARNING = "SUITABILITY_LOW_CONTRAST_WARNING"

    # Pose
    SUITABILITY_POSE_EXTREME = "SUITABILITY_POSE_EXTREME"
    SUITABILITY_POSE_WARNING = "SUITABILITY_POSE_WARNING"
    SUITABILITY_POSE_CHECK_UNAVAILABLE = "SUITABILITY_POSE_CHECK_UNAVAILABLE"

    # Head completeness
    SUITABILITY_HEAD_TOP_CLIPPED = "SUITABILITY_HEAD_TOP_CLIPPED"
    SUITABILITY_HEAD_SIDE_CLIPPED = "SUITABILITY_HEAD_SIDE_CLIPPED"
    SUITABILITY_CHIN_CLIPPED = "SUITABILITY_CHIN_CLIPPED"
    SUITABILITY_BEARD_BOUNDARY_CLIPPED = "SUITABILITY_BEARD_BOUNDARY_CLIPPED"
    SUITABILITY_HEAD_COMPLETENESS_UNAVAILABLE = (
        "SUITABILITY_HEAD_COMPLETENESS_UNAVAILABLE"
    )

    # Eyes & occlusion
    SUITABILITY_EYES_NOT_VISIBLE = "SUITABILITY_EYES_NOT_VISIBLE"
    SUITABILITY_FACE_OCCLUDED = "SUITABILITY_FACE_OCCLUDED"
    SUITABILITY_OCCLUSION_CHECK_UNAVAILABLE = "SUITABILITY_OCCLUSION_CHECK_UNAVAILABLE"

    # Transparency
    SUITABILITY_EXCESSIVE_TRANSPARENCY = "SUITABILITY_EXCESSIVE_TRANSPARENCY"
    SUITABILITY_ALPHA_WARNING = "SUITABILITY_ALPHA_WARNING"

    # Provider failures
    SUITABILITY_PROVIDER_UNAVAILABLE = "SUITABILITY_PROVIDER_UNAVAILABLE"
    SUITABILITY_PROVIDER_ERROR = "SUITABILITY_PROVIDER_ERROR"
    SUITABILITY_CHECK_INDETERMINATE = "SUITABILITY_CHECK_INDETERMINATE"

    # Head estimation details
    SUITABILITY_HEAD_ESTIMATION_UNAVAILABLE = "SUITABILITY_HEAD_ESTIMATION_UNAVAILABLE"
    SUITABILITY_HEAD_ESTIMATION_FAILED = "SUITABILITY_HEAD_ESTIMATION_FAILED"
    SUITABILITY_HEAD_ESTIMATION_LOW_CONFIDENCE = (
        "SUITABILITY_HEAD_ESTIMATION_LOW_CONFIDENCE"
    )
    SUITABILITY_HEAD_BOX_INVALID = "SUITABILITY_HEAD_BOX_INVALID"
    SUITABILITY_HEAD_BOX_CLAMPED = "SUITABILITY_HEAD_BOX_CLAMPED"
    SUITABILITY_HAIR_BOUNDARY_UNCERTAIN = "SUITABILITY_HAIR_BOUNDARY_UNCERTAIN"
    SUITABILITY_EAR_VISIBILITY_UNKNOWN = "SUITABILITY_EAR_VISIBILITY_UNKNOWN"
    SUITABILITY_HEAD_COVERING_UNCERTAIN = "SUITABILITY_HEAD_COVERING_UNCERTAIN"

    # Segmentation failures & warnings
    SEGMENTATION_PROVIDER_UNAVAILABLE = "SEGMENTATION_PROVIDER_UNAVAILABLE"
    SEGMENTATION_PROVIDER_FAILED = "SEGMENTATION_PROVIDER_FAILED"
    SEGMENTATION_MODEL_MISSING = "SEGMENTATION_MODEL_MISSING"
    SEGMENTATION_MODEL_CHECKSUM_FAILED = "SEGMENTATION_MODEL_CHECKSUM_FAILED"
    SEGMENTATION_OUTPUT_INVALID = "SEGMENTATION_OUTPUT_INVALID"
    SEGMENTATION_MASK_EMPTY = "SEGMENTATION_MASK_EMPTY"
    SEGMENTATION_MASK_FULL_FRAME = "SEGMENTATION_MASK_FULL_FRAME"
    SEGMENTATION_MASK_DIMENSION_MISMATCH = "SEGMENTATION_MASK_DIMENSION_MISMATCH"
    SEGMENTATION_MASK_NONFINITE = "SEGMENTATION_MASK_NONFINITE"
    SEGMENTATION_FACE_NOT_CONTAINED = "SEGMENTATION_FACE_NOT_CONTAINED"
    SEGMENTATION_HEAD_REGION_LOW_COVERAGE = "SEGMENTATION_HEAD_REGION_LOW_COVERAGE"
    SEGMENTATION_FOREGROUND_FRAGMENTED = "SEGMENTATION_FOREGROUND_FRAGMENTED"
    SEGMENTATION_MULTIPLE_MAJOR_COMPONENTS = "SEGMENTATION_MULTIPLE_MAJOR_COMPONENTS"
    SEGMENTATION_FOREGROUND_COVERAGE_LOW = "SEGMENTATION_FOREGROUND_COVERAGE_LOW"
    SEGMENTATION_FOREGROUND_COVERAGE_HIGH = "SEGMENTATION_FOREGROUND_COVERAGE_HIGH"
    SEGMENTATION_EDGE_CONTACT_WARNING = "SEGMENTATION_EDGE_CONTACT_WARNING"
    SEGMENTATION_UNCERTAIN_EDGE_HIGH = "SEGMENTATION_UNCERTAIN_EDGE_HIGH"
